ipBroker=localhost
portBroker=3000
tcp=false
x=0
y=0
seed=100
sizeDistributionMode=e
sizeDistributionParam1=1
sizeDistributionParam2=0
delayDistributionMode=e
delayDistributionParam1=0.8
delayDistributionParam2=0
mobilityDistributionMode=d
mobilityDistributionParam1=0
mobilityDistributionParam2=0
