ipBroker=localhost
portBroker=3000
tcp=true
x=0
y=0
seed=0
sizeDistributionMode=e
sizeDistributionParam1=1
sizeDistributionParam2=1
delayDistributionMode=e
delayDistributionParam1=1
delayDistributionParam2=1
mobilityDistributionMode=d
mobilityDistributionParam1=0
mobilityDistributionParam2=0
